document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("  <meta charset=\'utf-8\'>");
document.writeln("<meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0\'/>");
document.writeln("");
document.writeln("");
document.writeln("  <title>BlockSys'2019</title>");
document.writeln("  <meta content=\'width=device-width, initial-scale=1.0\' name=\'viewport\'>");
document.writeln("  <meta content=\'\' name=\'keywords\'>");
document.writeln("  <meta content=\'\' name=\'description\'>");
document.writeln("  <meta content=\'Author\' name=\'WebThemez\'>");
document.writeln("  <!-- Favicons -->");
document.writeln("  <link href=\'img/favicon.png\' rel=\'icon\'>");
document.writeln("  <link href=\'img/apple-touch-icon.png\' rel=\'apple-touch-icon\'>");
document.writeln("");
document.writeln("  <!-- Google Fonts -->");
document.writeln("  <link href=\'https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Raleway:300,400,500,700,800|Montserrat:300,400,700\' rel=\'stylesheet\'>");
document.writeln("");
document.writeln("  <!-- Bootstrap CSS File -->");
document.writeln("  <link href=\'lib/bootstrap/css/bootstrap.min.css\' rel=\'stylesheet\'>");
document.writeln("");
document.writeln("  <!-- Libraries CSS Files -->");
document.writeln("  <link href=\'lib/font-awesome/css/font-awesome.min.css\' rel=\'stylesheet\'>");
document.writeln("  <link href=\'lib/animate/animate.min.css\' rel=\'stylesheet\'>");
document.writeln("  <link href=\'lib/ionicons/css/ionicons.min.css\' rel=\'stylesheet\'>");
document.writeln("  <link href=\'lib/owlcarousel/assets/owl.carousel.min.css\' rel=\'stylesheet\'>");
document.writeln("  <link href=\'lib/magnific-popup/magnific-popup.css\' rel=\'stylesheet\'>");
document.writeln("  <link href=\'lib/ionicons/css/ionicons.min.css\' rel=\'stylesheet\'>");
document.writeln("");
document.writeln("  <!-- Main Stylesheet File -->");
document.writeln("  <link href=\'css/style.css\' rel=\'stylesheet\'> ");
document.writeln("</head>");
document.writeln("");
document.writeln("<body id=\'body\'>");
document.writeln("");
document.writeln("  <!--==========================");
document.writeln("    Top Bar");
document.writeln("  ============================-->");
document.writeln("  ");
document.writeln("    </div>");
document.writeln("  </section>");
document.writeln("");
document.writeln("  <!--==========================");
document.writeln("    Header");
document.writeln("  ============================-->");
document.writeln("  <header id=\'header\'>");
document.writeln("    <div class=\'container\'>");
document.writeln("");
document.writeln("      <div id=\'logo\' class=\'pull-left\'>");
document.writeln("        <h1><a href=\'index.html\' class=\'scrollto\'><span></span>BlockSys'2019</a></h1> ");
document.writeln("        <!-- <a href=\'#body\'><img src=\'img/logo.png\' alt=\'\' title=\'\' /></a>-->");
document.writeln("      </div>");
document.writeln("");
document.writeln("     <nav id=\'nav-menu-container\'>");
document.writeln("        <ul class=\'nav-menu\'>");
document.writeln("          <li class=\'menu-has-children\' position:relative><a href=\'call.html\'>Call for Papers</a>");
document.writeln("<ul>");
document.writeln("              <li><a href=\'call.html\'>Research Track</a></li>");
document.writeln("              <li><a href=\'about.html\'>EPA Track</a></li>");
document.writeln("              <li><a href=\'#\'>Industry Track</a></li>");
document.writeln("              <li><a href=\'#\'>Tool Demo Track</a></li>");
document.writeln("<li><a href=\'#\'>RENE Track</a></li>");
document.writeln("              <li><a href=\'#\'>Workshop Track</a></li>");
document.writeln("              <li><a href=\'#\'>Joumal First Track</a></li>");
document.writeln("            </ul></li>");
document.writeln("          <li><a href=\'registration.html\'>Registration</a></li>");
document.writeln("          <li><a href=\'program.html\'>Program</a></li>");
document.writeln("          <li class=\'menu-has-children\' position:relative><a href=\'#\'>Committee</a>");
document.writeln("            <ul>");
document.writeln("              <li><a href=\'organizing.html\'>Organizing Committee</a></li>");
document.writeln("              <li><a href=\'#\'>Program Committee</a></li>");
document.writeln("            </ul>");
document.writeln("          </li>");
document.writeln("          <li><a href=\'Venue.html\'>Venue</a></li>");
document.writeln("          <li class=\'menu-has-children\' position:relative><a href=\'#\'>Travel</a>");
document.writeln("            <ul>");
document.writeln("              <li><a href=\'transportation.html\'>Transportation</a></li>");
document.writeln("              <li><a href=\'guangzhou.html\'>About Guangzhou</a></li>");
document.writeln("            </ul>");
document.writeln("          </li>");
document.writeln("        ");
document.writeln("      </nav><!-- #nav-menu-container -->");
document.writeln("    </div>");
document.writeln("");
document.writeln("  </header><!-- #header -->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("  <!-- JavaScript  -->");
document.writeln("  <script src=\'lib/jquery/jquery.min.js\'></script>");
document.writeln("  <script src=\'lib/jquery/jquery-migrate.min.js\'></script>");
document.writeln("  <script src=\'lib/bootstrap/js/bootstrap.bundle.min.js\'></script>");
document.writeln("  <script src=\'lib/easing/easing.min.js\'></script>");
document.writeln("  <script src=\'lib/superfish/hoverIntent.js\'></script>");
document.writeln("  <script src=\'lib/superfish/superfish.min.js\'></script>");
document.writeln("  <script src=\'lib/wow/wow.min.js\'></script>");
document.writeln("  <script src=\'lib/owlcarousel/owl.carousel.min.js\'></script>");
document.writeln("  <script src=\'lib/magnific-popup/magnific-popup.min.js\'></script>");
document.writeln("  <script src=\'lib/sticky/sticky.js\'></script> ");
document.writeln(" <script src=\'contact/jqBootstrapValidation.js\'></script>");
document.writeln(" <script src=\'contact/contact_me.js\'></script>");
document.writeln("  <script src=\'js/main.js\'></script>");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");
document.writeln("");